---
- name: Collect web mgmt admins
  tags: haproxy
  set_fact:
    localWebMgmtAdmins: "{{ localWebMgmtAdmins | union(item.members) }}"
  with_items:
   - "{{ userRoles }}"
  when: item.roleName == webPrivilegedAccessGroup

- name: Local web mgmt admins attributes
  tags: haproxy
  set_fact:
    localWebMgmtAdminsAttributes: "{{ localWebMgmtAdmins | map('extract', userAccounts ) | list }}"

- name: Deploy HAProxy config
  tags: haproxy
  template:
    src: "{{ item }}.j2"
    dest: "/etc/haproxy/{{ item }}"
    owner: root
    group: root
    mode: "u=rw,g=r"
  notify: restart haproxy
  with_items:
   - haproxy.cfg

- name: Start HAproxy Service
  tags: haproxy
  service: name=haproxy state=started enabled=yes

